spring.application.name=prova_bussola

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/prova_bussola
spring.datasource.username=postgres
spring.datasource.password=post